name: Hello World

# This workflow is triggered on push and pull request events
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs
jobs:
  # This job runs on the latest Ubuntu runner
  hello-world:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Say Hello World
        run: echo "Hello World!"

      # Print current date
      - name: Show current date
        run: date

      # Show directory contents in long format
      - name: Show directory contents
        run: ls -l
